# Preparación de Datos

1.1 Carga de datos

1.2 Limpieza de datos

1.3 Exploración inicial: Realiza un análisis descriptivo para entender la estructura y las características del conjunto de datos.

In [1]:
import numpy as np
import pandas as pd
from unidecode import unidecode
import re

# Importar datos

In [3]:
# iniciamos nuestro proyecto, cargando la tabla con la que vamos a trabajar

In [11]:
tdata = pd.read_csv("male_teams.csv")
tdata.head()

,team_id,team_url,fifa_version,fifa_update,update_as_of,team_name,league_id,league_name,league_level,nationality_id,...,off_corners,off_free_kicks,build_up_play_speed,build_up_play_dribbling,build_up_play_passing,build_up_play_positioning,chance_creation_passing,chance_creation_crossing,chance_creation_shooting,chance_creation_positioning
0,1,/team/1/arsenal/150002,15,2,2014-09-18,Arsenal,13,Premier League,1.0,14,...,NaN,NaN,59.0,51.0,26.0,Organised,28.0,55.0,63.0,Free Form
1,2,/team/2/aston-villa/150002,15,2,2014-09-18,Aston Villa,13,Premier League,1.0,14,...,NaN,NaN,66.0,32.0,72.0,Organised,63.0,48.0,56.0,Organised
2,3,/team/3/blackburn-rovers/150002,15,2,2014-09-18,Blackburn Rovers,14,Championship,2.0,14,...,NaN,NaN,44.0,31.0,62.0,Organised,63.0,61.0,40.0,Organised
3,4,/team/4/bolton-wanderers/150002,15,2,2014-09-18,Bolton Wanderers,14,League One,2.0,14,...,NaN,NaN,57.0,37.0,73.0,Organised,72.0,38.0,56.0,Organised
4,5,/team/5/chelsea/150002,15,2,2014-09-18,Chelsea,13,Premier League,1.0,14,...,NaN,NaN,67.0,52.0,38.0,Organised,41.0,61.0,63.0,Organised

## Familiarizando con los datos

In [4]:
tdata.shape

(6947, 54)

In [5]:
# utilizamos un bucle para conocer el nombre de todas las columnas de nuestra tabla

for i, j in enumerate(tdata.columns, 1):
    print(i, j)

1 team_id
2 team_url
3 fifa_version
4 fifa_update
5 update_as_of
6 team_name
7 league_id
8 league_name
9 league_level
10 nationality_id
11 nationality_name
12 overall
13 attack
14 midfield
15 defence
16 coach_id
17 home_stadium
18 rival_team
19 international_prestige
20 domestic_prestige
21 transfer_budget_eur
22 club_worth_eur
23 starting_xi_average_age
24 whole_team_average_age
25 captain
26 short_free_kick
27 long_free_kick
28 left_short_free_kick
29 right_short_free_kick
30 penalties
31 left_corner
32 right_corner
33 def_style
34 def_team_width
35 def_team_depth
36 def_defence_pressure
37 def_defence_aggression
38 def_defence_width
39 def_defence_defender_line
40 off_style
41 off_build_up_play
42 off_chance_creation
43 off_team_width
44 off_players_in_box
45 off_corners
46 off_free_kicks
47 build_up_play_speed
48 build_up_play_dribbling
49 build_up_play_passing
50 build_up_play_positioning
51 chance_creation_passing
52 chance_creation_crossing
53 chance_creation_shooting
54 chance_creation_positioning

### Valores nulos por columna

In [6]:
# usamos el siguiente bucle para identificar aquellas columnas
# en las que existen valores nulos

for i, j in enumerate(tdata.columns, 1):
    nulos = tdata[j].isnull().sum()
    print(f'{i} {j:35}: {nulos}  nulos')

1 team_id                            : 0  nulos
2 team_url                           : 0  nulos
3 fifa_version                       : 0  nulos
4 fifa_update                        : 0  nulos
5 update_as_of                       : 0  nulos
6 team_name                          : 0  nulos
7 league_id                          : 0  nulos
8 league_name                        : 0  nulos
9 league_level                       : 450  nulos
10 nationality_id                     : 0  nulos
11 nationality_name                   : 0  nulos
12 overall                            : 0  nulos
13 attack                             : 0  nulos
14 midfield                           : 0  nulos
15 defence                            : 0  nulos
16 coach_id                           : 37  nulos
17 home_stadium                       : 12  nulos
18 rival_team                         : 0  nulos
19 international_prestige             : 0  nulos
20 domestic_prestige                  : 436  nulos
21 transfer_budget_eur                : 1785  nulos
22 club_worth_eur                     : 1618  nulos
23 starting_xi_average_age            : 0  nulos
24 whole_team_average_age             : 0  nulos
25 captain                            : 38  nulos
26 short_free_kick                    : 39  nulos
27 long_free_kick                     : 40  nulos
28 left_short_free_kick               : 41  nulos
29 right_short_free_kick              : 39  nulos
30 penalties                          : 47  nulos
31 left_corner                        : 42  nulos
32 right_corner                       : 40  nulos
33 def_style                          : 2653  nulos
34 def_team_width                     : 2653  nulos
35 def_team_depth                     : 2653  nulos
36 def_defence_pressure               : 3595  nulos
37 def_defence_aggression             : 3595  nulos
38 def_defence_width                  : 3595  nulos
39 def_defence_defender_line          : 3595  nulos
40 off_style                          : 4801  nulos
41 off_build_up_play                  : 4799  nulos
42 off_chance_creation                : 4799  nulos
43 off_team_width                     : 2653  nulos
44 off_players_in_box                 : 2653  nulos
45 off_corners                        : 2653  nulos
46 off_free_kicks                     : 2653  nulos
47 build_up_play_speed                : 3595  nulos
48 build_up_play_dribbling            : 3595  nulos
49 build_up_play_passing              : 3595  nulos
50 build_up_play_positioning          : 3595  nulos
51 chance_creation_passing            : 3595  nulos
52 chance_creation_crossing           : 3595  nulos
53 chance_creation_shooting           : 3595  nulos
54 chance_creation_positioning        : 3595  nulos

### Tipos de datos por columna

In [7]:
# es necesario conocer el tipo de dato que manejaremos en este proyecto,
# por lo que pasamos a desglosarlo por columna

for i, j in enumerate(tdata.columns, 1):
    tipo = tdata[j].dtypes
    print(f'{i} {j:35}: {tipo}')

1 team_id                            : int64
2 team_url                           : object
3 fifa_version                       : int64
4 fifa_update                        : int64
5 update_as_of                       : object
6 team_name                          : object
7 league_id                          : int64
8 league_name                        : object
9 league_level                       : float64
10 nationality_id                     : int64
11 nationality_name                   : object
12 overall                            : int64
13 attack                             : int64
14 midfield                           : int64
15 defence                            : int64
16 coach_id                           : float64
17 home_stadium                       : object
18 rival_team                         : int64
19 international_prestige             : int64
20 domestic_prestige                  : float64
21 transfer_budget_eur                : float64
22 club_worth_eur                     : float64
23 starting_xi_average_age            : float64
24 whole_team_average_age             : float64
25 captain                            : float64
26 short_free_kick                    : float64
27 long_free_kick                     : float64
28 left_short_free_kick               : float64
29 right_short_free_kick              : float64
30 penalties                          : float64
31 left_corner                        : float64
32 right_corner                       : float64
33 def_style                          : object
34 def_team_width                     : float64
35 def_team_depth                     : float64
36 def_defence_pressure               : float64
37 def_defence_aggression             : float64
38 def_defence_width                  : float64
39 def_defence_defender_line          : object
40 off_style                          : object
41 off_build_up_play                  : object
42 off_chance_creation                : object
43 off_team_width                     : float64
44 off_players_in_box                 : float64
45 off_corners                        : float64
46 off_free_kicks                     : float64
47 build_up_play_speed                : float64
48 build_up_play_dribbling            : float64
49 build_up_play_passing              : float64
50 build_up_play_positioning          : object
51 chance_creation_passing            : float64
52 chance_creation_crossing           : float64
53 chance_creation_shooting           : float64
54 chance_creation_positioning        : object

### Consulta filas duplicadas

In [8]:
print("Filas duplicadas:", tdata.duplicated().sum())  
tdata.drop_duplicates(inplace=True)

Filas duplicadas: 0

# Trabajo con columnas

## Eliminacion de columnas irrelevantes

In [9]:
# tras el analisis anterior, tomamos la decision de prescindir de las siguientes columnas,
# ya que no intervienen de manera significativa en nuetro objetivo

col_eliminadas = ["team_name", "fifa_update", "update_as_of", "league_level", "coach_id", "home_stadium", "rival_team", 
            "international_prestige", "domestic_prestige", "transfer_budget_eur", "club_worth_eur", "captain", 
            "short_free_kick", "long_free_kick", "left_short_free_kick", "right_short_free_kick", "penalties", 
            "left_corner", "right_corner", "def_style", "def_team_width", "def_team_depth", "def_defence_pressure", 
            "def_defence_aggression", "def_defence_width", "def_defence_defender_line", "off_style", 
            "off_build_up_play", "off_chance_creation", "off_team_width", "off_players_in_box", "off_corners", 
            "off_free_kicks", "build_up_play_speed", "build_up_play_dribbling", "build_up_play_passing", 
            "build_up_play_positioning", "chance_creation_passing", "chance_creation_crossing", 
            "chance_creation_shooting", "chance_creation_positioning"
 ]
tdata = tdata.drop(col_eliminadas, axis = 1)

## Cambio de nomenclatura

In [10]:
# decidimos traducir y hacer mas legible nuestra tabla con estos cambios

nuevos_nombres_columnas = {
    "fifa_version":"version", "team_name":"nombre_club", "league_id":"id_liga", "league_name":"nombre_liga", "nationality_id":"id_nacionalidad",
    "nationality_name":"nacion_liga", "overall":"est_general", "attack":"ataque", "midfield":"mediocampo", "defence":"defensa",
    "starting_xi_average_age":"promedio_edad_titulares", "whole_team_average_age":"promedio_edad_equipo", 'team_url': 'nombre_club', 'team_id': 'id_equipo'					
}
tdata.rename(columns = nuevos_nombres_columnas, inplace=True)

## Comprobacion de valores nulos

In [11]:
tdata.isnull().sum()

id_equipo                  0
nombre_club                0
version                    0
id_liga                    0
nombre_liga                0
id_nacionalidad            0
nacion_liga                0
est_general                0
ataque                     0
mediocampo                 0
defensa                    0
promedio_edad_titulares    0
promedio_edad_equipo       0
dtype: int64

## Cambiando el tipo de dato

In [12]:
tdata.dtypes

id_equipo                    int64
nombre_club                 object
version                      int64
id_liga                      int64
nombre_liga                 object
id_nacionalidad              int64
nacion_liga                 object
est_general                  int64
ataque                       int64
mediocampo                   int64
defensa                      int64
promedio_edad_titulares    float64
promedio_edad_equipo       float64
dtype: object

In [13]:
tdata['version'] = '20' + tdata['version'].astype(str)
tdata['version'] = tdata['version'].astype(int)

# Modificacion de valores

## Transformando la columna 'team_url'

In [14]:
# seguimos un proceso parecido al de la tabla 'players' y la columna 'player_url'. Es una manera de sacar el
# nombre del los clubes sin caracteres especiales.
def extraer_nombre(team_url):
    partes = team_url.split('/')
    nombre = partes[-2]    
    nombre_formateado = re.sub(r'\b\w', lambda x: x.group(0).title(), nombre).replace('-', ' ')
    return nombre_formateado
tdata["nombre_club"] = tdata['nombre_club'].apply(extraer_nombre)

In [15]:
# aqui comprobamos que efectivamente no hay caracteres especiales y ponemos la primera letra en mayuscula

In [16]:
tdata['nombre_liga'] = tdata['nombre_liga'].str.replace(r'[^a-zA-Z0-9\s]', '', regex=True)
tdata['nombre_liga'] = tdata['nombre_liga'].str.title()

## Traduciendo la columna 'nacion_liga'

In [17]:
p = {"England": "Inglaterra","Germany": "Alemania","Italy": "Italia", "France": "Francia", "Scotland": "Escocia", "Austria": "Austria",
    "Belgium": "Bélgica","Portugal": "Portugal","Spain": "España", "Netherlands": "Países Bajos","Denmark": "Dinamarca","Greece": "Grecia",
    "Switzerland": "Suiza","Norway": "Noruega","Republic of Ireland": "República de Irlanda","Russia": "Rusia","Sweden": "Suecia",
    "Turkey": "Turquía","Poland": "Polonia","Saudi Arabia": "Arabia Saudita","United States": "Estados Unidos","Korea Republic": "República de Corea",
    "Argentina": "Argentina","Mexico": "México","Bulgaria": "Bulgaria", "Czech Republic": "Republica Checa", "Finland": "Finlandia",
    "Romania": "Rumania","Slovenia": "Eslovenia", "Wales": "Gales", "Brazil": "Brasil","Paraguay": "Paraguay","Uruguay": "Uruguay","Cameroon": "Camerún",
    "Australia": "Australia","Hungary": "Hungría","Chile": "Chile","Ukraine": "Ucrania","Colombia": "Colombia","Northern Ireland": "Irlanda del Norte",
    "South Africa": "Sudáfrica","Peru": "Perú","Côte d'Ivoire": "Costa de Marfil","Egypt": "Egipto","Bolivia": "Bolivia","Ecuador": "Ecuador",
    "India": "India","New Zealand": "Nueva Zelanda","Venezuela": "Venezuela","China PR": "China","Canada": "Canadá","Japan": "Japón",
    "Iceland": "Islandia","Croatia": "Croacia","United Arab Emirates": "Emiratos Arabes Unidos","Cyprus": "Chipre","Monaco": "Mónaco",
    "Morocco": "Marruecos","Ghana": "Ghana","Qatar": "Catar"}

tdata['nacion_liga'] = tdata['nacion_liga'].replace(p)
tdata['nacion_liga'] = tdata['nacion_liga'].str.title()
tdata['nacion_liga'] = tdata['nacion_liga'].apply(unidecode)

In [18]:
tdata

,id_equipo,nombre_club,version,id_liga,nombre_liga,id_nacionalidad,nacion_liga,est_general,ataque,mediocampo,defensa,promedio_edad_titulares,promedio_edad_equipo
0,1,Arsenal,2015,13,Premier League,14,Inglaterra,81,82,80,78,25.09,23.82
1,2,Aston Villa,2015,13,Premier League,14,Inglaterra,74,76,74,73,26.00,24.64
2,3,Blackburn Rovers,2015,14,Championship,14,Inglaterra,68,69,67,65,26.00,24.57
3,4,Bolton Wanderers,2015,14,League One,14,Inglaterra,68,67,69,67,27.09,25.57
4,5,Chelsea,2015,13,Premier League,14,Inglaterra,82,83,82,81,25.64,23.76
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6942,116360,Chengdu Rongcheng,2024,2012,Super League,155,China,65,70,63,66,30.45,29.14
6943,116361,Wuhan Three Towns,2024,2012,Super League,155,China,68,74,67,68,28.91,27.61
6944,131110,Eldense,2024,54,La Liga 2,45,Espana,68,68,66,67,28.27,26.64
6945,131173,Qingdao Hainiu,2024,2012,Super League,155,China,62,70,62,62,30.36,30.32
6946,131389,Pendikspor,2024,68,Super Lig,48,Turquia,69,70,70,68,27.82,28.14

In [19]:
tdata.isnull().sum()

id_equipo                  0
nombre_club                0
version                    0
id_liga                    0
nombre_liga                0
id_nacionalidad            0
nacion_liga                0
est_general                0
ataque                     0
mediocampo                 0
defensa                    0
promedio_edad_titulares    0
promedio_edad_equipo       0
dtype: int64

In [20]:
tdata['nombre_club'] = tdata.nombre_club.str.lower()
tdata['nombre_liga'] = tdata.nombre_liga.str.lower()
tdata['nacion_liga'] = tdata.nacion_liga.str.lower()

In [21]:
tdata

,id_equipo,nombre_club,version,id_liga,nombre_liga,id_nacionalidad,nacion_liga,est_general,ataque,mediocampo,defensa,promedio_edad_titulares,promedio_edad_equipo
0,1,arsenal,2015,13,premier league,14,inglaterra,81,82,80,78,25.09,23.82
1,2,aston villa,2015,13,premier league,14,inglaterra,74,76,74,73,26.00,24.64
2,3,blackburn rovers,2015,14,championship,14,inglaterra,68,69,67,65,26.00,24.57
3,4,bolton wanderers,2015,14,league one,14,inglaterra,68,67,69,67,27.09,25.57
4,5,chelsea,2015,13,premier league,14,inglaterra,82,83,82,81,25.64,23.76
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6942,116360,chengdu rongcheng,2024,2012,super league,155,china,65,70,63,66,30.45,29.14
6943,116361,wuhan three towns,2024,2012,super league,155,china,68,74,67,68,28.91,27.61
6944,131110,eldense,2024,54,la liga 2,45,espana,68,68,66,67,28.27,26.64
6945,131173,qingdao hainiu,2024,2012,super league,155,china,62,70,62,62,30.36,30.32
6946,131389,pendikspor,2024,68,super lig,48,turquia,69,70,70,68,27.82,28.14

# Creando archivo .CSV

In [22]:
# convertimos nuestro archivo modificado de Python en otro .CSV para unirlo a la tabla 'data'.

In [23]:
tdata.to_csv('tdata.csv', index=False)